############### English navigation ################

[[main]]
name = "About"
url = "post/about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3

# Dropdown menu
[[main]]
weight = 4
name = "Products"
hasChildren = true

[[main]]
parent = "Products"
name = "AWS Batch"
url = "/batch/"
weight = 1

[[main]]
parent = "Products"
name = "AWS ParallelCluster"
url = "/parallelcluster/"
weight = 2

[[main]]
parent = "Products"
name = "Elastic Fabric Adapter"
url = "/efa/"
weight = 3

[[main]]
parent = "Products"
name = "NICE DCV"
url = "/nice-dcv/"
weight = 4

[[main]]
weight = 5
name = "Workloads"
hasChildren = true

[[main]]
parent = "Workloads"
name = "AI/ML"
url = "/categories/ai/ml"
weight = 1

[[main]]
parent = "Workloads"
name = "CAE/CFD"
url = "/categories/cae/cfd/"
weight = 2

[[main]]
parent = "Workloads"
name = "Climate, Environment & Weather"
url = "/categories/climate/environment/weather"
weight = 3

[[main]]
parent = "Workloads"
name = "Financial Services"
url = "/categories/financial-services/"
weight = 3

[[main]]
parent = "Workloads"
name = "Life Sciences"
url = "/categories/life-sciences/"
weight = 4

[[main]]
weight = 6
name = "Resources"
hasChildren = true

# footer "Quick Links" menu
[[footer]]
name = "About"
url = "post/about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2
