############### English navigation ################

# Dropdown menu
# [[main]]
# weight = 1
# name = "homepage"
# hasChildren = true

# [[main]]
# parent = "homepage"
# name = "Homepage Full Width"
# url = "homepage/full/"
# weight = 1

# [[main]]
# parent = "homepage"
# name = "Homepage Full With Left Sidebar"
# url = "homepage/full-left/"
# weight = 2

# [[main]]
# parent = "homepage"
# name = "Homepage Full With Right Sidebar"
# url = "homepage/full-right/"
# weight = 3

# [[main]]
# parent = "homepage"
# name = "Homepage List Style"
# url = "homepage/list/"
# weight = 4

# [[main]]
# parent = "homepage"
# name = "Homepage List With Left Sidebar"
# url = "homepage/list-left/"
# weight = 5

# [[main]]
# parent = "homepage"
# name = "Homepage List With Right Sidebar"
# url = "homepage/list-right/"
# weight = 6

# [[main]]
# parent = "homepage"
# name = "Homepage Grid Style"
# url = "homepage/grid/"
# weight = 7

# [[main]]
# parent = "homepage"
# name = "Homepage Grid With Left Sidebar"
# url = "homepage/grid-left/"
# weight = 8

# [[main]]
# parent = "homepage"
# name = "Homepage Grid With Right Sidebar"
# url = "homepage/grid-right/"
# weight = 9


[[main]]
name = "About"
url = "post/about/"
weight = 2

[[main]]
name = "Learning"
url = "learning/"
weight = 3

# Dropdown menu
[[main]]
weight = 4
name = "Products"
hasChildren = true

[[main]]
parent = "Products"
name = "AWS Batch"
url = "/batch/"
weight = 1

[[main]]
parent = "Products"
name = "AWS ParallelCluster"
url = "/parallelcluster/"
weight = 2

[[main]]
parent = "Products"
name = "Elastic Fabric Adapter"
url = "/efa/"
weight = 3

[[main]]
parent = "Products"
name = "NICE DCV"
url = "/nice-dcv/"
weight = 4

[[main]]
weight = 5
name = "Workloads"
hasChildren = true

[[main]]
parent = "Workloads"
name = "Life Sciences"
url = "/categories/life-sciences/"
weight = 1

[[main]]
parent = "Workloads"
name = "CAE/CFD"
url = "/categories/cae-cfd/"
weight = 2

[[main]]
parent = "Workloads"
name = "Machine Learning"
url = "/categories/ml-ai/"
weight = 3

[[main]]
parent = "Workloads"
name = "Weather and Climate"
url = "/categories/weather-climate/"
weight = 4

[[main]]
parent = "Workloads"
name = "Financial Services"
url = "/categories/financial/"
weight = 5

# [[main]]
# parent = "Pages"
# name = "Search"
# url = "http://demo.gethugothemes.com/logbook/search/?s=image/"
# weight = 5

[[main]]
weight = 6
name = "Resources"
hasChildren = true

# footer "Quick Links" menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Learning"
url = "learning/"
weight = 1

# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3

# [[footer]]
# name = "Terms Conditions"
# url = "terms-conditions/"
# weight = 4
