############### English navigation ################

[[main]]
weight = 2
name = "Learn"
url = "/learning/"
hasChildren = true

# Dropdown menu
[[main]]
weight = 3
name = "Products"
hasChildren = true

[[main]]
parent = "Products"
name = "AWS Batch"
url = "/batch/"
weight = 1

[[main]]
parent = "Products"
name = "AWS ParallelCluster"
url = "/parallelcluster/"
weight = 2

[[main]]
parent = "Products"
name = "Elastic Fabric Adapter"
url = "/efa/"
weight = 3

[[main]]
parent = "Products"
name = "NICE DCV"
url = "/nice-dcv/"
weight = 4

# [[main]]
# weight = 4
# name = "Workloads"
# hasChildren = true
# 
# [[main]]
# parent = "Workloads"
# name = "AI/ML"
# url = "/ai-ml/"
# weight = 1
# 
# [[main]]
# parent = "Workloads"
# name = "CAE/CFD"
# url = "/cae-cfd/"
# weight = 2
# 
# [[main]]
# parent = "Workloads"
# name = "Climate, Environment & Weather"
# url = "/climate-environment-weather/"
# weight = 3
# 
# [[main]]
# parent = "Workloads"
# name = "Life Sciences"
# url = "/life-sciences/"
# weight = 4

[[main]]
weight = 5
name = "About"
url = "about/"
hasChildren = false

# [[main]]
# weight = 6
# name = "Resources"
# url = "/resources/"
# hasChildren = false

# footer "Quick Links" menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2
