baseURL = "http://day1hpc-staging.s3-website.us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "Day 1 HPC (Staging)"

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$", ".webp$"]

[[deployment.targets]]
URL = "s3://day1hpc-staging?region=us-east-1"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf|webp)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
