---
label: Post
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- name: author
  type: select
  default: Brendan Bouffler
  config:
    required: true
    options:
    - Brendan Bouffler
    - " Matt Vaughn"
    - Angel Pizarro
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Author
- type: text
  name: description
  label: description
- type: image_gallery
  name: images
  label: images
- type: list
  name: categories
  label: categories
- type: list
  name: tags
  label: tags
- name: type
  type: select
  default: regular
  config:
    required: false
    options:
    - regular
    - featured
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
