---
label: Post
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    max: 70
- type: datetime
  name: date
  label: Date
  default: now
- name: author
  type: select
  default: Brendan Bouffler
  config:
    required: true
    options:
    - Brendan Bouffler
    - " Matt Vaughn"
    - Angel Pizarro
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Author
- type: text
  name: description
  label: Description
  config:
    required: true
    max: 210
- type: image_gallery
  name: images
  label: Images
- name: type
  type: select
  default: regular
  config:
    required: false
    options:
    - regular
    - featured
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
- name: categories
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: simple
    options:
    - AWS ParallelCluster
    - AWS Batch
    - Amazon EFA
    - AWS NICE DCV
    - Life Sciences
    - CFD/CAE
    - ML/AI
    - Financial Services
    - Weather/Climate
  label: Categories
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- content/english/post/meep.md
